### ISSUE TITLE
failed to select a version for `unicode-normalization` which could resolve this conflict

### ISSUE THREAD

**Issue by jiker-burce** [rust-nostr/nostr-desktop#5]
```
➜  nostr-desktop git:(master) cargo run          
    Updating git repository `https://github.com/yukibtc/nostr-rs-sdk.git`
    Updating `ustc` index
error: failed to select a version for `unicode-normalization`.
    ... required by package `bip39 v1.0.0`
    ... which satisfies dependency `bip39 = "^1.0"` of package `nostr v0.12.0 (https://github.com/yukibtc/nostr-rs-sdk.git?rev=7496698c2e040e34b70e804665b8b28aa3a989e7#7496698c)`
    ... which satisfies git dependency `nostr` of package `nostr-sdk v0.12.0 (https://github.com/yukibtc/nostr-rs-sdk.git?rev=7496698c2e040e34b70e804665b8b28aa3a989e7#7496698c)`
    ... which satisfies git dependency `nostr-sdk` of package `nostr-desktop v0.1.0 (/Users/gujinhe/my-tool/rust/nostr/nostr-desktop)`
versions that meet the requirements `=0.1.9` are: 0.1.9

all possible versions conflict with previously selected packages.

  previously selected package `unicode-normalization v0.1.22`
    ... which satisfies dependency `unicode-normalization = "^0.1.22"` (locked to 0.1.22) of package `idna v0.5.0`
    ... which satisfies dependency `idna = "^0.5.0"` (locked to 0.5.0) of package `url v2.5.0`
    ... which satisfies dependency `url = "^2.2"` (locked to 2.5.0) of package `reqwest v0.11.27`
    ... which satisfies dependency `reqwest = "^0.11.13"` (locked to 0.11.27) of package `nostr-desktop v0.1.0 (/Users/gujinhe/my-tool/rust/nostr/nostr-desktop)`

failed to select a version for `unicode-normalization` which could resolve this conflict
➜  nostr-desktop git:(master) 

```

**Comment by aki-mizu** [comment]
It seems you're using a mirror crate registry from ustc that might be outdated.
There's no issues compiling from official crates.io registry.
Can you try using official registry or update your ustc mirror cache?

**Comment by jiker-burce** [comment]
I have changed several image sources, but all of then show the same errors when I run `cargo run`.
But I could run  the examples of `nostr-sdk` without any problems. @aki-mizu

**Comment by yukibtc** [comment]
A temp solution (before the bump of `nostr-sdk` dep) could be to disable the default features for `nostr-sdk` and enable only the ones needed.

The `nip06` feature enable the bip39 dep, that depends on `unicode-normalization`.

**Comment by aki-mizu** [comment]
@jiker-burce 
Can you try `cargo update url --precise 2.3.0` first then `cargo run`?
Please provide error logs after running above command.

**Comment by jiker-burce** [comment]
> cargo run

It works, the main frame is displayed. There is no error showed this time. 

So maybe the latest version exists some potential problems?
<img width="1402" alt="image" src="https://github.com/rust-nostr/nostr-desktop/assets/24581223/5f4b9ef5-0996-472b-8ffc-2a7f2b42274b">

<img width="1013" alt="image" src="https://github.com/rust-nostr/nostr-desktop/assets/24581223/bb41cb2c-b916-4e77-8913-498786b1bb8d">

**Comment by aki-mizu** [comment]
Thanks for the feedback. 
Yes, some dependency used in this project is not updated yet. It will be updated sometime in the future.
